import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from './ThemeContext'
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Chat from "@/components/ModalChat/Chat";

export const metadata: Metadata = {
  title: "Start Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ThemeProvider>
          <Chat/>
          <NavBar />
          {children}
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
